### PR TITLE
Add to ptr method to matrix4

### PR DESCRIPTION
**Pull request by Yavuz1234567890**

### CODE REVIEW

**Comment by kacperks** [comment]
I'll commit this my self, This pr makes conflict with My last commit

**Comment by Yavuz1234567890** [comment]
u can copy past it

**Comment by kacperks** [comment]
I know

**Comment by kacperks** [comment]
Can u open new pr with this?
I'll accept it

**Comment by Yavuz1234567890** [comment]
u say its not works

**Pull request closed without merging**
